### ISSUE TITLE
Finish the exercise!

### ISSUE THREAD

**Issue by oneeyedman** [Adalab/f-m2-evaluacion-intermedia-AranchaAdalab#1]
Hi, @AranchaAdalab  !!!

You are close to the exercise solution, but here you have a steps guide to complete it anyway ;)

1. Save a reference to DOM elements in variables
2. Generate the random number and save it to a variable
3. Init counter of trials to 0
4. Define a function that executes when the user clicks on the button, that
  - increments the counter and paints its value in the HTML
  - collect the value of the HTML input and compare it with the random number
    - if they are equal, draw a 'You Win' message
    - if it's lower, draw a 'Too short' message
    - if it's higher, draw a 'Too long' message
5. Assign a listener to the button click to execute the previous function

Then you can improve the game as you please, here you have some ideas:

- Add new feedback when the number is bigger than 100 or smaller than 0.
- Manage when the user hits the button and the input is empty.
- Make the input work when hitting enter key.
- Add a reset button that cleans the input, the counter, writes the initial feedback and generates a new random number to play again!
- Whatever you want!

Let me know if you have any doubts ;)

Go for it!!

**Comment by AranchaAdalab** [comment]
Hi @oneeyedman 

I tried to improve the game, but there are some things that I don't know how to do it (I tried them but I didn't get it):

- Make the input work when hitting enter key.
- Add a reset button that generates a new random number to play again.

I would appreciate if you can give me some clues.

Thank you!

**Comment by oneeyedman** [comment]
Oki, I'll try my best!!

Once you win the game, it would be great that a `reset` button appears so that the user can play again. This button should call a function that sets the counter back to zero and chooses another random number.

What do you think? Better? worse? 

You got this!

![Yoy got this](https://media.giphy.com/media/11F0d3IVhQbreE/giphy-downsized.gif)

**Comment by AranchaAdalab** [comment]
Hi @oneeyedman

I finished my exercise!

**Comment by oneeyedman** [comment]
YAY!! Well done @AranchaAdalab!

If you are up to a challenge check out these exercises from previous Adalabers:

- http://beta.adalab.es/dorcas-s2-evaluacion-intermedia-mariavioleta1417/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-maria-badanina/
- http://beta.adalab.es/dorcar-s2-evaluacion-intermedia-annabranco/
- http://beta.adalab.es/e-s2-evaluacion-intermedia-beatrizAdalab/

;)
